import type {
  AdminEvent,
  AdminInterest,
  AdminMember,
  AdminOpportunity,
  AuditLogEntry,
} from "./types"

/**
 * Dados de demonstração do painel. Substituir por consultas ao Supabase quando
 * o acesso ao projeto estiver disponível (ver camada em src/lib/admin/store).
 */

const now = new Date()
const iso = (daysAgo: number) => {
  const d = new Date(now)
  d.setDate(d.getDate() - daysAgo)
  return d.toISOString()
}

export const CURRENT_MONTH_LABEL = now.toLocaleDateString("pt-BR", {
  month: "long",
  year: "numeric",
})

export const MOCK_MEMBERS: AdminMember[] = [
  {
    id: "m-001",
    profileId: "u-001",
    fullName: "Ana Beatriz Alencar",
    displayName: "Ana Alencar",
    email: "ana.alencar@example.com",
    phone: "(88) 99999-0001",
    city: "Juazeiro do Norte",
    state: "CE",
    bio: "Founder de uma healthtech focada em telemedicina no interior do Cariri.",
    photoUrl: null,
    company: "SaudeCariri",
    position: "CEO",
    occupationAreas: ["founder", "empresario"],
    interests: ["startups", "saude", "impacto-social"],
    needs: ["Buscar investimento", "Encontrar talentos"],
    offers: ["Mentoria", "Palestras"],
    socialLinks: [{ platform: "linkedin", url: "https://linkedin.com/in/anaalencar" }],
    status: "approved",
    role: "admin",
    isPublic: true,
    createdAt: iso(120),
  },
  {
    id: "m-002",
    profileId: "u-002",
    fullName: "Carlos Henrique Bezerra",
    displayName: "Carlos Bezerra",
    email: "carlos.bezerra@example.com",
    phone: "(88) 99999-0002",
    city: "Crato",
    state: "CE",
    bio: "Desenvolvedor full-stack apaixonado por comunidades de tecnologia.",
    photoUrl: null,
    company: "Freelancer",
    position: "Dev",
    occupationAreas: ["desenvolvedor"],
    interests: ["tecnologia", "programacao", "inteligencia-artificial"],
    needs: ["Conhecer pessoas", "Participar de eventos"],
    offers: ["Desenvolvimento", "Mentoria"],
    socialLinks: [{ platform: "github", url: "https://github.com/chbezerra" }],
    status: "approved",
    role: "curator",
    isPublic: true,
    createdAt: iso(96),
  },
  {
    id: "m-003",
    profileId: "u-003",
    fullName: "Mariana Sousa Lima",
    displayName: "Mari Lima",
    email: "mariana.lima@example.com",
    phone: null,
    city: "Barbalha",
    state: "CE",
    bio: "Designer de produto e entusiasta de economia criativa.",
    photoUrl: null,
    company: "Estúdio Verde",
    position: "Product Designer",
    occupationAreas: ["designer"],
    interests: ["economia-criativa", "ux-ui", "produto"],
    needs: ["Divulgar projeto", "Conectar com empresas"],
    offers: ["Design", "Produto"],
    socialLinks: [{ platform: "instagram", url: "https://instagram.com/marilima" }],
    status: "approved",
    role: "member",
    isPublic: true,
    createdAt: iso(70),
  },
  {
    id: "m-004",
    profileId: "u-004",
    fullName: "João Pedro Tavares",
    displayName: "João Tavares",
    email: "joao.tavares@example.com",
    phone: "(88) 99999-0004",
    city: "Juazeiro do Norte",
    state: "CE",
    bio: null,
    photoUrl: null,
    company: null,
    position: null,
    occupationAreas: ["estudante"],
    interests: ["tecnologia", "startups"],
    needs: ["Aprender sobre startups"],
    offers: [],
    socialLinks: [],
    status: "pending",
    role: "member",
    isPublic: false,
    createdAt: iso(2),
  },
  {
    id: "m-005",
    profileId: "u-005",
    fullName: "Fernanda Rocha Menezes",
    displayName: "Fernanda Menezes",
    email: "fernanda.menezes@example.com",
    phone: "(88) 99999-0005",
    city: "Crato",
    state: "CE",
    bio: "Investidora-anjo com foco em agtechs e impacto social no semiárido.",
    photoUrl: null,
    company: "Sertão Ventures",
    position: "Partner",
    occupationAreas: ["investidor"],
    interests: ["agro", "impacto-social", "captacao-recursos"],
    needs: ["Divulgar projeto"],
    offers: ["Investimento", "Mentoria", "Conexão institucional"],
    socialLinks: [{ platform: "linkedin", url: "https://linkedin.com/in/fmenezes" }],
    status: "approved",
    role: "member",
    isPublic: true,
    createdAt: iso(45),
  },
  {
    id: "m-006",
    profileId: "u-006",
    fullName: "Rafael Gomes da Silva",
    displayName: "Rafael Gomes",
    email: "rafael.gomes@example.com",
    phone: null,
    city: "Fortaleza",
    state: "CE",
    bio: "Professor universitário e pesquisador em IA aplicada ao agronegócio.",
    photoUrl: null,
    company: "URCA",
    position: "Professor",
    occupationAreas: ["professor", "pesquisador"],
    interests: ["inteligencia-artificial", "agro", "educacao"],
    needs: ["Encontrar talentos", "Acessar editais"],
    offers: ["Pesquisa", "Palestras"],
    socialLinks: [],
    status: "pending",
    role: "member",
    isPublic: false,
    createdAt: iso(1),
  },
  {
    id: "m-007",
    profileId: "u-007",
    fullName: "Larissa Oliveira Campos",
    displayName: "Larissa Campos",
    email: "larissa.campos@example.com",
    phone: "(88) 99999-0007",
    city: "Barbalha",
    state: "CE",
    bio: "Especialista em marketing digital para pequenos negócios.",
    photoUrl: null,
    company: "Cria Agência",
    position: "Head de Marketing",
    occupationAreas: ["marketing_vendas"],
    interests: ["vendas-negocios", "economia-criativa"],
    needs: ["Conectar com empresas", "Receber oportunidades"],
    offers: ["Marketing", "Vendas"],
    socialLinks: [{ platform: "instagram", url: "https://instagram.com/lariscampos" }],
    status: "approved",
    role: "member",
    isPublic: true,
    createdAt: iso(30),
  },
  {
    id: "m-008",
    profileId: "u-008",
    fullName: "Diego Martins Feitosa",
    displayName: "Diego Feitosa",
    email: "diego.feitosa@example.com",
    phone: null,
    city: "Juazeiro do Norte",
    state: "CE",
    bio: null,
    photoUrl: null,
    company: null,
    position: null,
    occupationAreas: ["interessado_inovacao"],
    interests: ["startups"],
    needs: [],
    offers: [],
    socialLinks: [],
    status: "blocked",
    role: "member",
    isPublic: false,
    createdAt: iso(88),
  },
  {
    id: "m-009",
    profileId: "u-009",
    fullName: "Patrícia Nunes Aragão",
    displayName: "Patrícia Aragão",
    email: "patricia.aragao@example.com",
    phone: "(88) 99999-0009",
    city: "Crato",
    state: "CE",
    bio: "Mentora de negócios e ex-executiva de varejo.",
    photoUrl: null,
    company: "Consultoria PA",
    position: "Consultora",
    occupationAreas: ["mentor", "empresario"],
    interests: ["vendas-negocios", "startups", "captacao-recursos"],
    needs: ["Conhecer pessoas"],
    offers: ["Mentoria", "Gestão"],
    socialLinks: [{ platform: "linkedin", url: "https://linkedin.com/in/paragao" }],
    status: "approved",
    role: "member",
    isPublic: true,
    createdAt: iso(15),
  },
  {
    id: "m-010",
    profileId: "u-010",
    fullName: "Bruno Carvalho Pinto",
    displayName: "Bruno Pinto",
    email: "bruno.pinto@example.com",
    phone: null,
    city: "Missão Velha",
    state: "CE",
    bio: "Estudante de engenharia, curioso por robótica e hardware.",
    photoUrl: null,
    company: null,
    position: null,
    occupationAreas: ["estudante", "desenvolvedor"],
    interests: ["tecnologia", "industria", "programacao"],
    needs: ["Aprender sobre startups", "Encontrar mentores"],
    offers: ["Desenvolvimento"],
    socialLinks: [],
    status: "pending",
    role: "member",
    isPublic: false,
    createdAt: iso(5),
  },
  {
    id: "m-011",
    profileId: "u-011",
    fullName: "Camila Ferreira Duarte",
    displayName: "Camila Duarte",
    email: "camila.duarte@example.com",
    phone: "(88) 99999-0011",
    city: "Juazeiro do Norte",
    state: "CE",
    bio: "Gestora pública dedicada a políticas de inovação.",
    photoUrl: null,
    company: "Prefeitura",
    position: "Secretária Adjunta",
    occupationAreas: ["parceiro_institucional"],
    interests: ["editais", "impacto-social", "educacao"],
    needs: ["Conectar com empresas"],
    offers: ["Conexão institucional", "Parcerias"],
    socialLinks: [],
    status: "approved",
    role: "member",
    isPublic: true,
    createdAt: iso(22),
  },
  {
    id: "m-012",
    profileId: "u-012",
    fullName: "Thiago Andrade Moreira",
    displayName: "Thiago Moreira",
    email: "thiago.moreira@example.com",
    phone: null,
    city: "Fortaleza",
    state: "CE",
    bio: null,
    photoUrl: null,
    company: "Loft Digital",
    position: "CTO",
    occupationAreas: ["desenvolvedor", "founder"],
    interests: ["tecnologia", "inteligencia-artificial", "produto"],
    needs: ["Encontrar sócio"],
    offers: ["Desenvolvimento", "Produto"],
    socialLinks: [{ platform: "website", url: "https://loftdigital.com.br" }],
    status: "rejected",
    role: "member",
    isPublic: false,
    createdAt: iso(60),
  },
  {
    id: "m-013",
    profileId: "u-013",
    fullName: "Juliana Barros Teixeira",
    displayName: "Juliana Teixeira",
    email: "juliana.teixeira@example.com",
    phone: "(88) 99999-0013",
    city: "Crato",
    state: "CE",
    bio: "Pesquisadora em turismo e desenvolvimento regional.",
    photoUrl: null,
    company: "IFCE",
    position: "Pesquisadora",
    occupationAreas: ["pesquisador", "professor"],
    interests: ["turismo", "economia-criativa", "educacao"],
    needs: ["Acessar editais", "Divulgar projeto"],
    offers: ["Pesquisa", "Conteúdo"],
    socialLinks: [],
    status: "approved",
    role: "member",
    isPublic: true,
    createdAt: iso(8),
  },
  {
    id: "m-014",
    profileId: "u-014",
    fullName: "Gustavo Lima Freitas",
    displayName: "Gustavo Freitas",
    email: "gustavo.freitas@example.com",
    phone: null,
    city: "Barbalha",
    state: "CE",
    bio: null,
    photoUrl: null,
    company: null,
    position: null,
    occupationAreas: ["interessado_inovacao"],
    interests: ["startups", "tecnologia"],
    needs: ["Conhecer pessoas"],
    offers: [],
    socialLinks: [],
    status: "pending",
    role: "member",
    isPublic: false,
    createdAt: iso(0),
  },
  {
    id: "m-015",
    profileId: "u-015",
    fullName: "Isabela Cardoso Ramos",
    displayName: "Isabela Ramos",
    email: "isabela.ramos@example.com",
    phone: "(88) 99999-0015",
    city: "Juazeiro do Norte",
    state: "CE",
    bio: "Empreendedora social no setor de educação.",
    photoUrl: null,
    company: "EducaCariri",
    position: "Fundadora",
    occupationAreas: ["founder", "professor"],
    interests: ["educacao", "impacto-social", "startups"],
    needs: ["Buscar investimento", "Encontrar talentos"],
    offers: ["Palestras", "Mentoria"],
    socialLinks: [{ platform: "linkedin", url: "https://linkedin.com/in/isaramos" }],
    status: "approved",
    role: "member",
    isPublic: true,
    createdAt: iso(12),
  },
  {
    id: "m-016",
    profileId: "u-016",
    fullName: "Pedro Henrique Nogueira",
    displayName: "Pedro Nogueira",
    email: "pedro.nogueira@example.com",
    phone: null,
    city: "Iguatu",
    state: "CE",
    bio: "Analista de dados iniciando na comunidade.",
    photoUrl: null,
    company: null,
    position: null,
    occupationAreas: ["desenvolvedor"],
    interests: ["inteligencia-artificial", "programacao"],
    needs: ["Encontrar oportunidades"],
    offers: ["Desenvolvimento"],
    socialLinks: [],
    status: "approved",
    role: "member",
    isPublic: true,
    createdAt: iso(3),
  },
  {
    id: "m-017",
    profileId: "u-017",
    fullName: "Beatriz Sampaio Costa",
    displayName: "Bia Costa",
    email: "beatriz.costa@example.com",
    phone: "(88) 99999-0017",
    city: "Crato",
    state: "CE",
    bio: "UX writer e designer de conteúdo.",
    photoUrl: null,
    company: "Freelancer",
    position: "UX Writer",
    occupationAreas: ["designer", "marketing_vendas"],
    interests: ["ux-ui", "economia-criativa", "produto"],
    needs: ["Receber oportunidades"],
    offers: ["Design", "Conteúdo"],
    socialLinks: [{ platform: "instagram", url: "https://instagram.com/biacosta" }],
    status: "approved",
    role: "member",
    isPublic: true,
    createdAt: iso(6),
  },
  {
    id: "m-018",
    profileId: "u-018",
    fullName: "Marcelo Vasconcelos Pires",
    displayName: "Marcelo Pires",
    email: "marcelo.pires@example.com",
    phone: null,
    city: "Juazeiro do Norte",
    state: "CE",
    bio: null,
    photoUrl: null,
    company: "Indústria Cariri",
    position: "Gerente",
    occupationAreas: ["empresario"],
    interests: ["industria", "vendas-negocios"],
    needs: ["Conectar com empresas"],
    offers: ["Parcerias"],
    socialLinks: [],
    status: "blocked",
    role: "member",
    isPublic: false,
    createdAt: iso(50),
  },
]

export const MOCK_INTERESTS: AdminInterest[] = [
  { id: "i-01", name: "Startups", slug: "startups", category: "Setores", active: true, memberCount: 9 },
  { id: "i-02", name: "Tecnologia", slug: "tecnologia", category: "Setores", active: true, memberCount: 8 },
  { id: "i-03", name: "Inteligência Artificial", slug: "inteligencia-artificial", category: "Setores", active: true, memberCount: 4 },
  { id: "i-04", name: "Agro", slug: "agro", category: "Setores", active: true, memberCount: 2 },
  { id: "i-05", name: "Turismo", slug: "turismo", category: "Setores", active: true, memberCount: 1 },
  { id: "i-06", name: "Economia Criativa", slug: "economia-criativa", category: "Setores", active: true, memberCount: 4 },
  { id: "i-07", name: "Educação", slug: "educacao", category: "Setores", active: true, memberCount: 4 },
  { id: "i-08", name: "Saúde", slug: "saude", category: "Setores", active: true, memberCount: 1 },
  { id: "i-09", name: "Impacto Social", slug: "impacto-social", category: "Setores", active: true, memberCount: 4 },
  { id: "i-10", name: "Indústria", slug: "industria", category: "Setores", active: false, memberCount: 2 },
  { id: "i-11", name: "Vendas e Negócios", slug: "vendas-negocios", category: "Negócios", active: true, memberCount: 3 },
  { id: "i-12", name: "Captação de Recursos", slug: "captacao-recursos", category: "Negócios", active: true, memberCount: 2 },
  { id: "i-13", name: "Editais", slug: "editais", category: "Negócios", active: true, memberCount: 1 },
  { id: "i-14", name: "Produto", slug: "produto", category: "Habilidades", active: true, memberCount: 3 },
  { id: "i-15", name: "UX/UI", slug: "ux-ui", category: "Habilidades", active: true, memberCount: 2 },
  { id: "i-16", name: "Programação", slug: "programacao", category: "Habilidades", active: true, memberCount: 3 },
]

export const MOCK_EVENTS: AdminEvent[] = [
  {
    id: "e-01",
    title: "Kariri Valley Meetup #1",
    description: "Primeiro encontro presencial da comunidade para networking e apresentação de projetos.",
    startsAt: iso(-14),
    location: "Juazeiro do Norte, CE",
    capacity: 80,
    registrationsCount: 52,
    status: "published",
  },
  {
    id: "e-02",
    title: "Workshop: Do zero ao MVP",
    description: "Oficina prática de validação e construção de MVPs para founders iniciantes.",
    startsAt: iso(-30),
    location: "Crato, CE",
    capacity: 40,
    registrationsCount: 0,
    status: "draft",
  },
  {
    id: "e-03",
    title: "Demo Day Cariri 2025",
    description: "Startups da comunidade apresentam para investidores e parceiros.",
    startsAt: iso(45),
    location: "Barbalha, CE",
    capacity: 120,
    registrationsCount: 120,
    status: "past",
  },
]

export const MOCK_OPPORTUNITIES: AdminOpportunity[] = [
  {
    id: "o-01",
    title: "Edital de Aceleração Sertão Ventures",
    description: "Programa de aceleração para startups em estágio inicial do Cariri.",
    type: "edital",
    deadline: iso(-20),
    tags: ["aceleração", "investimento", "early-stage"],
    status: "open",
  },
  {
    id: "o-02",
    title: "Vaga: Desenvolvedor(a) Full-stack",
    description: "Vaga remota para healthtech da comunidade.",
    type: "vaga",
    deadline: iso(-10),
    tags: ["remoto", "react", "node"],
    status: "open",
  },
  {
    id: "o-03",
    title: "Programa de Mentoria em Gestão",
    description: "Ciclo de mentorias com executivos parceiros.",
    type: "mentoria",
    deadline: null,
    tags: ["gestão", "mentoria"],
    status: "draft",
  },
]

export const MOCK_LOGS: AuditLogEntry[] = [
  {
    id: "l-01",
    timestamp: iso(1),
    actorName: "Ana Alencar",
    actorRole: "admin",
    action: "approve_member",
    targetType: "member",
    targetName: "Pedro Nogueira",
  },
  {
    id: "l-02",
    timestamp: iso(3),
    actorName: "Ana Alencar",
    actorRole: "admin",
    action: "block_member",
    targetType: "member",
    targetName: "Diego Feitosa",
    details: "Comportamento inadequado reportado.",
  },
  {
    id: "l-03",
    timestamp: iso(4),
    actorName: "Carlos Bezerra",
    actorRole: "curator",
    action: "approve_member",
    targetType: "member",
    targetName: "Beatriz Costa",
  },
]
